## Makefile for building wireshark.exe with Microsoft C and nmake
## Use: $(MAKE) /$(MAKEFLAGS) -f makefile.nmake
#
# $Id: Makefile.nmake 21347 2007-04-06 15:51:36Z grahamb $

include ..\..\config.nmake

CFLAGS=-WX -D_U_="" $(LOCAL_CFLAGS)

.c.obj::
   $(CC) $(CFLAGS) -Fd.\ -c $<

all : lemon.exe

clean:
	rm -f lemon.obj lemon.exe lemon.ilk *.pdb lemon.exe.manifest

distclean: clean

maintainer-clean: distclean
