'\" t
.\"     Title: asn2deb
.\"    Author: W. Borgert
.\" Generator: DocBook XSL Stylesheets v1.75.2 <http://docbook.sf.net/>
.\"      Date: 2004-02-18
.\"    Manual: [FIXME: manual]
.\"    Source: [FIXME: source]
.\"  Language: English
.\"
.TH "ASN2DEB" "1" "2004\-02\-18" "[FIXME: source]" "[FIXME: manual]"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
asn2deb \- create a Debian package for BER monitoring from ASN\&.1
.SH "SYNOPSIS"
.HP \w'\fBasn2deb\fR\ 'u
\fBasn2deb\fR [\-a\ \fIASN\&.1\ file\fR] [\-\-asn=\fIASN\&.1\ file\fR] [\fB\-d\ \fR\fB\fIopts\fR\fR] [\fB\-\-dbopts=\fR\fB\fIopts\fR\fR] [\fB\-e\ \fR\fB\fIaddress\fR\fR] [\fB\-\-email=\fR\fB\fIaddress\fR\fR] [\fB\-h\fR] [\fB\-\-help\fR] [\fB\-n\ \fR\fB\fIname\fR\fR] [\fB\-\-name=\fR\fB\fIname\fR\fR] [\fB\-p\fR] [\fB\-\-preserve\fR] [\fB\-v\fR] [\fB\-\-version\fR]
.SH "DESCRIPTION"
.PP
This manual page documents briefly the
\fBasn2deb\fR
command\&.
.PP
\fBasn2deb\fR
takes an ASN\&.1 file as input and creates a Debian package from it\&. The package contains a loadable type table file for the wireshark network analyser\&. The type table is generated by the ASN\&.1 compiler
\fBsnacc\fR\&.
.SH "OPTIONS"
.PP
\fB\-a \fR\fB\fIASN\&.1 file\fR\fR \fB\-\-asn=\fR\fB\fIASN\&.1 file\fR\fR
.RS 4
ASN\&.1 file to use (mandatory)\&.
.RE
.PP
\fB\-d \fR\fB\fIopts\fR\fR \fB\-\-dbopts=\fR\fB\fIopts\fR\fR
.RS 4
options for dpkg\-buildpackage\&.
.RE
.PP
\fB\-e \fR\fB\fIaddress\fR\fR \fB\-\-email=\fR\fB\fIaddress\fR\fR
.RS 4
use e\-mail address\&.
.RE
.PP
\fB\-h\fR \fB\-\-help\fR
.RS 4
print help and exit\&.
.RE
.PP
\fB\-n \fR\fB\fIname\fR\fR \fB\-\-name=\fR\fB\fIname\fR\fR
.RS 4
use user name\&.
.RE
.PP
\fB\-p\fR \fB\-\-preserve\fR
.RS 4
do not overwrite files\&.
.RE
.PP
\fB\-v\fR \fB\-\-version\fR
.RS 4
print version and exit\&.
.RE
.PP
Example:
.sp
.if n \{\
.RS 4
.\}
.nf
/usr/bin/asn2deb \-e me@foo\&.net \-a bar\&.asn1 \e
\-n "My Name" \-d "\-rfakeroot \-uc \-us"
.fi
.if n \{\
.RE
.\}
.SH "SEE ALSO"
.PP
A lot of tools are used, which you have to
\fBapt\-get install\fR: wireshark\-dev, python, cdbs, autotools\-dev, debhelper, dpkg\-dev, snacc\&.
.SH "COPYING"
.PP
This manual page was written by W\&. Borgert
debacle@debian\&.org
for
Debian GNU/Linux
(but may be used by others)\&. Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation\&.
.SH "AUTHOR"
.PP
\fBW\&. Borgert\fR
.RS 4
Author.
.RE
.SH "COPYRIGHT"
.br
Copyright \(co 2003, 2005 W. Borgert
.br
